version: '3.1'

services:
  nginx:
    depends_on:
      - app
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # network_mode: host

# https://www.bogotobogo.com/DevOps/Docker/Docker-Compose-Nginx-Reverse-Proxy-Multiple-Containers.php

  vault:
    image: hashicorp/vault:latest
    restart: always
    privileged: true
    cap_add: 
      - IPC_LOCK
    ports:
      - 8200
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=myroot"

  db:
    depends_on:
      - app
      - vault
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./pgdata/ips.sql:/docker-entrypoint-initdb.d/ips.sql
    # command: psql -f /var/lib/postgresql/data/ips.sql
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 10

  # volumes:
  #   pgdata

  app:
    depends_on:
      - vault
    build: .
    restart: always
    ports:
      - 5000
