version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
  
  vault:
    image: hashicorp/vault:latest
    restart: always
    privileged: true
    cap_add: 
      - IPC_LOCK
    ports:
      - 8200
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=myroot"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  app:
    build: .
    restart: always
    ports:
      - 5000:5000