version: '3.1'

services:
  nginx:
    depends_on:
      - app
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # network_mode: host
# https://www.bogotobogo.com/DevOps/Docker/Docker-Compose-Nginx-Reverse-Proxy-Multiple-Containers.php

  vault:
    depends_on:
      - db
    # image: vault:0.0.2
    image: hashicorp/vault:latest
    restart: always
    privileged: true
    cap_add: 
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=myroot"
      - "VAULT_ADDR=http://127.0.0.1:8200"
      - "VAULT_TOKEN=myroot"
    healthcheck:
      test: ["curl", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  vaultsetup:
    depends_on:
      - vault
    image: hashicorp/vault:latest
    restart: "no"
    volumes:
      - ./vault/vault_init.sh:/vault_init.sh
    command: sh -c "./vault_init.sh"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./pgdata/ips.sql:/docker-entrypoint-initdb.d/ips.sql

  app:
    depends_on:
      - vault
    build: .
    restart: always
    ports:
      - 5000
    environment:
      - "VAULT_TOKEN=myroot"
      - "VAULT_ADDR=http://0.0.0.0:8200"
